name: ci-cd
on: 
  push: 
    branches: ["main"] 
  workflow_dispatch: 

jobs: 
  ci: 
    runs-on: ubuntu-latest 
    steps:
      - name: Obter codigo 
        uses: actions/checkout@v4.2.2 
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Construir e enviar da imagem Docker 
        uses: docker/build-push-action@v6
        with:  
          context: ./src 
          push: true 
          file: ./src/Dockerfile 
          # tags: user/app:latest 
          tags:  
            # eliemarbueno/fake-shop:v${{ github.run_number }} 
            eliemarbueno/fake-shop:latest 
            
  cd:  
    needs: [ci] 
    runs-on: ubuntu-latest 
    steps: 
      - name: Obter codigo 
        uses: actions/checkout@v4.2.2 
      - run: echo "Configurar o kubeconfig" 
      - run: echo "Executar o apply" 
